Stop boxes-upgrade script if release_name can't be read in yaml file

diff --git a/files/release/boxes-upgrade b/files/release/boxes-upgrade
--- a/files/release/boxes-upgrade
+++ b/files/release/boxes-upgrade
@@ -12,7 +12,12 @@
 
 tar_file=$1
 current_file=$2
-release_name=`sed -n '/name/ s/name: //p' $current_file`
+
+release_name=`sed -n '/name:/ s/.*name: //p' $current_file`
+if [ -z "$release_name" ]; then
+    echo "Can't read release name in $current_file"
+    exit 1
+fi
 
 temp_dir=`mktemp -d "/srv/rivendell/tmp/boxes-upgrade-$release_name-XXXXXX"`
 
@@ -42,4 +47,3 @@ fi
 if [ -d "$temp_dir/rivendellnasbox" ]; then
     /usr/local/sbin/box-upgrade $temp_dir/rivendellnasbox/upgrade.tar $temp_dir/rivendellnasbox/latest.yml
 fi
-
